version: "3"
services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx-proxy-lab
      
networks:
    nginx-proxy-lab:
      external: true